using MailChimpWrapper.Endpoints;
using MailChimpWrapper.Helpers;
using MailChimpWrapper.Model;
using MailChimpWrapper.Model.Common;
using MailChimpWrapper.Model.List;
using MailChimpWrapper.Model.List.Filters;
using MailChimpWrapper.Model.List.Response;
using MailChimpWrapper.Serializers;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using static MailChimpWrapper.Action.Common;

namespace MailChimpWrapper.Action
{
    /// <summary>
    /// Class that encapsulates all methods from mailchimp
    /// relative to Lists
    /// </summary>
    public class ListAction : BaseAction
    {
        #region Constructor
        /// <summary>
        /// Public constructor
        /// </summary>
        /// <param name="apiKey">Client API Key generated by mailchimp</param>
        public ListAction(string apiKey) : base(apiKey)
        {
        }
        #endregion

        #region Create
        /// <summary>
        /// Creates a list on mailchimp
        /// </summary>
        /// <param name="list">The model that contains all info about the list that will be created</param>
        /// <returns></returns>
        public MailChimpWrapperResponse<ListCreateResponseModel> Create(ListCreateModel list)
        {
            try
            {                
                // Initialize the RestRequest from RestSharp.Newtonsoft so the serializer will user Newtonsoft defaults.
                var request = new RestRequest(ResourcesEndpoints.ListCreate(), Method.POST);
                // Adds the resource
                request.AddHeader("content-type", "application/json");
                request.JsonSerializer = new CustomNewtonsoftSerializer(new JsonSerializer()
                {
                    NullValueHandling = NullValueHandling.Ignore,
                });

                // Validates the object
                var validationContext = new ValidationContext(list, serviceProvider: null, items: null);
                var validationResults = new List<ValidationResult>();
                var isValid = Validator.TryValidateObject(list, validationContext, validationResults, false);

                if (isValid)
                {
                    request.AddJsonBody(list);
                    // Execute the request
                    var response = restClient.Execute(request);

                    // If the request return ok, then return MailChimpWrapperResponse with deserialized object
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        return new MailChimpWrapperResponse<ListCreateResponseModel>
                        {
                            objectRespose = JsonConvert.DeserializeObject<ListCreateResponseModel>(response.Content)
                        };

                    // Check If MailChimp is Offline
                    if (response.StatusCode == System.Net.HttpStatusCode.GatewayTimeout)
                        return ErrorResponse<ListCreateResponseModel>(new Exception("MailChimp Offline"));

                    // If an error occurs, encapsulates the error in MailChimpWrapperResponse
                    var errorContent = JsonConvert.DeserializeObject<ErrorModel>(response.Content);
                    return new MailChimpWrapperResponse<ListCreateResponseModel>
                    {
                        hasErrors = true,
                        error = errorContent
                    };
                }

                // If the object was not valid then creates and ErrorModel to send back
                var error = new ErrorModel
                {
                    type = "Internal Method Error.",
                    title = "One or more fields were not validated. Look in detail for more information",
                    status = 0,
                    detail = Util.GetValidationsErrors(validationResults)
                };
                return new MailChimpWrapperResponse<ListCreateResponseModel>
                {
                    hasErrors = true,
                    error = error
                };
            }
            catch (Exception ex)
            {
                return ErrorResponse<ListCreateResponseModel>(ex);
            }            
        }
        #endregion

        #region Read
        /// <summary>
        /// Read all lists from mailchimp
        /// </summary>
        /// <param name="options">The options to filter the lists result</param>
        /// <returns></returns>
        public MailChimpWrapperResponse<ListReadAllResponseModel> ReadAll(ListReadAllOptions options = null)
        {
            try
            {
                // Adds the resource
                var request = new RestRequest(ResourcesEndpoints.ListReadAll(), Method.GET);

                // Check if options was passed
                if (options != null)
                    SetReadAllOptions(ref request, options);

                // Execute the request
                var response = restClient.Execute(request);

                // If the request return ok, then return MailChimpWrapperResponse with deserialized object
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    return new MailChimpWrapperResponse<ListReadAllResponseModel>
                    {
                        objectRespose = JsonConvert.DeserializeObject<ListReadAllResponseModel>(response.Content)
                    };

                // If an error occurs, encapsulates the error in MailChimpWrapperResponse
                var errorContent = JsonConvert.DeserializeObject<ErrorModel>(response.Content);
                return new MailChimpWrapperResponse<ListReadAllResponseModel>
                {
                    hasErrors = true,
                    error = errorContent
                };
            }
            catch (Exception ex)
            {
                return ErrorResponse<ListReadAllResponseModel>(ex);
            }
        }

        /// <summary>
        /// Reads the list info
        /// </summary>
        /// <param name="listId">The id of the list that will be read</param>
        /// <param name="options">Options to filter the list that will be returned</param>
        public MailChimpWrapperResponse<ListReadResponseModel> Read(string listId, ListReadOptions options = null)
        {
            try
            {
                // Adds the resource
                var request = new RestRequest(ResourcesEndpoints.ListRead(listId), Method.GET);

                // Check if options was passed
                if (options != null)
                    SetReadOptions(ref request, options);

                // Execute the request
                var response = restClient.Execute(request);

                // If the request return ok, then return MailChimpWrapperResponse with deserialized object
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    return new MailChimpWrapperResponse<ListReadResponseModel>
                    {
                        objectRespose = JsonConvert.DeserializeObject<ListReadResponseModel>(response.Content)
                    };

                // If an error occurs, encapsulates the error in MailChimpWrapperResponse
                var errorContent = JsonConvert.DeserializeObject<ErrorModel>(response.Content);
                return new MailChimpWrapperResponse<ListReadResponseModel>
                {
                    hasErrors = true,
                    error = errorContent
                };
            }
            catch (Exception ex)
            {
                return ErrorResponse<ListReadResponseModel>(ex);
            }
            
        }
        #endregion

        #region Update
        /// <summary>
        /// Updates the list by its id based on ListCreateModel object
        /// </summary>
        /// <param name="listId">The Id of the list to be updated</param>
        /// <param name="list">The model that contains all info about the list that will be created</param>
        /// <returns></returns>
        public MailChimpWrapperResponse<ListCreateResponseModel> Update(string listId, ListCreateModel list)
        {
            try
            {
                // Initialize the RestRequest from RestSharp.Newtonsoft so the serializer will user Newtonsoft defaults.
                var request = new RestRequest(ResourcesEndpoints.ListEdit(listId), Method.PATCH);
                // Adds the resource
                request.AddHeader("content-type", "application/json");
                request.JsonSerializer = new CustomNewtonsoftSerializer(new JsonSerializer()
                {
                    NullValueHandling = NullValueHandling.Ignore,
                });

                // Validates the object
                var validationContext = new ValidationContext(list, serviceProvider: null, items: null);
                var validationResults = new List<ValidationResult>();
                var isValid = Validator.TryValidateObject(list, validationContext, validationResults, false);

                if (isValid)
                {
                    request.AddJsonBody(list);
                    // Execute the request
                    var response = restClient.Execute(request);

                    // If the request return ok, then return MailChimpWrapperResponse with deserialized object
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        return new MailChimpWrapperResponse<ListCreateResponseModel>
                        {
                            objectRespose = JsonConvert.DeserializeObject<ListCreateResponseModel>(response.Content)
                        };

                    // If an error occurs, encapsulates the error in MailChimpWrapperResponse
                    var errorContent = JsonConvert.DeserializeObject<ErrorModel>(response.Content);
                    return new MailChimpWrapperResponse<ListCreateResponseModel>
                    {
                        hasErrors = true,
                        error = errorContent
                    };
                }

                // If the object was not valid then creates and ErrorModel to send back
                var error = new ErrorModel
                {
                    type = "Internal Method Error.",
                    title = string.Format("Field {0} missing", validationResults[0]?.MemberNames.FirstOrDefault()),
                    status = 0,
                    detail = validationResults[0].ErrorMessage
                };
                return new MailChimpWrapperResponse<ListCreateResponseModel>
                {
                    hasErrors = true,
                    error = error
                };
            }
            catch (Exception ex)
            {
                return ErrorResponse<ListCreateResponseModel>(ex);
            }
        }
        #endregion

        #region Delete
        /// <summary>
        /// Delete a list based on id.
        /// </summary>
        /// <param name="listId">The Id of the list to be deleted.</param>
        /// <returns></returns>
        public MailChimpWrapperResponse<CommonDeleteResponseModel> Delete(string listId)
        {
            try
            {
                // Adds the resource
                var request = new RestRequest(ResourcesEndpoints.ListDelete(listId), Method.DELETE);

                // Execute the request
                var response = restClient.Execute(request);

                // If the request return ok, then return MailChimpWrapperResponse with deserialized object
                if (response.StatusCode == System.Net.HttpStatusCode.NoContent)
                    return new MailChimpWrapperResponse<CommonDeleteResponseModel>
                    {
                        objectRespose = new CommonDeleteResponseModel()
                    };

                // If an error occurs, encapsulates the error in MailChimpWrapperResponse
                var errorContent = JsonConvert.DeserializeObject<ErrorModel>(response.Content);
                return new MailChimpWrapperResponse<CommonDeleteResponseModel>
                {
                    hasErrors = true,
                    error = errorContent
                };
            }
            catch (Exception ex)
            {
                return ErrorResponse<CommonDeleteResponseModel>(ex);
            }            
        }
        #endregion

        #region Private Auxiliary Methods
        /// <summary>
        /// Set on the request all the filters from ListReadAllOptions
        /// </summary>
        /// <param name="request">Request that will be used to call the API</param>
        /// <param name="options">Object with the options of filter for mailchimp call</param>
        private void SetReadAllOptions(ref RestRequest request, ListReadAllOptions options)
        {
            if (options.fields != null && options.fields.Count > 0)
            {
                var fieldsString = "";
                for (var i = 0; i < options.fields.Count; i++)
                {
                    if (i < options.fields.Count - 1)
                        fieldsString += options.fields[i] + ",";
                    else
                        fieldsString += options.fields[i];
                }
                request.AddQueryParameter("fields", fieldsString);
            }

            if (options.exclude_fields != null && options.exclude_fields.Count > 0)
            {
                var excludeFieldsString = "";
                for (var i = 0; i < options.exclude_fields.Count; i++)
                {
                    if (i < options.fields.Count - 1)
                        excludeFieldsString += options.exclude_fields[i] + ",";
                    else
                        excludeFieldsString += options.exclude_fields[i];
                }
                request.AddQueryParameter("exclude_fields", excludeFieldsString);
            }

            if (options.count != null)
                request.AddQueryParameter("count", ((int)options.count).ToString());

            if (options.offset != null)
                request.AddQueryParameter("offset", ((int)options.offset).ToString());

            if (!string.IsNullOrEmpty(options.before_date_created))
                request.AddQueryParameter("before_date_created", options.before_date_created);

            if (!string.IsNullOrEmpty(options.since_date_created))
                request.AddQueryParameter("since_date_created", options.since_date_created);

            if (!string.IsNullOrEmpty(options.before_campaign_last_sent))
                request.AddQueryParameter("before_campaign_last_sent", options.before_campaign_last_sent);

            if (!string.IsNullOrEmpty(options.since_campaign_last_sent))
                request.AddQueryParameter("since_campaign_last_sent", options.since_campaign_last_sent);

        }

        /// <summary>
        /// Set on the request all the filters from ListReadAllOptions
        /// </summary>
        /// <param name="request">Request that will be used to call the API</param>
        /// <param name="options">Object with the options of filter for mailchimp call</param>
        private void SetReadOptions(ref RestRequest request, ListReadOptions options)
        {
            if (options.fields != null && options.fields.Count > 0)
            {
                var fieldsString = "";
                for (var i = 0; i < options.fields.Count; i++)
                {
                    if (i < options.fields.Count - 1)
                        fieldsString += options.fields[i] + ",";
                    else
                        fieldsString += options.fields[i];
                }
                request.AddQueryParameter("fields", fieldsString);
            }

            if (options.exclude_fields != null && options.exclude_fields.Count > 0)
            {
                var excludeFieldsString = "";
                for (var i = 0; i < options.exclude_fields.Count; i++)
                {
                    if (i < options.fields.Count - 1)
                        excludeFieldsString += options.exclude_fields[i] + ",";
                    else
                        excludeFieldsString += options.exclude_fields[i];
                }
                request.AddQueryParameter("exclude_fields", excludeFieldsString);
            }
        }        
        #endregion
    }
}